### ISSUE TITLE
关于阿里oss

### ISSUE THREAD

**Issue by taoguo1** [shuyudao/sadfile#4]
感谢您提供的平台，我搭建了七牛云，一切正常，但是用阿里oss的话文件无法上传，能提供下您的思路吗？

**Comment by shuyudao** [comment]
> 感谢您提供的平台，我搭建了七牛云，一切正常，但是用阿里oss的话文件无法上传，能提供下您的思路吗？

不支持阿里oss，这个我很久以前写的项目了，抱歉
